version: '3.8'

services:
  airflow:
    image: apache/airflow:2.6.0
    container_name: airflow
    ports:
      - "8080:8080"
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__WEBSERVER__ENABLE_PROXY_FIX=True
    volumes:
      - ./dags:/opt/airflow/dags
    command: ["standalone"]

  rest_api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: rest_api
    ports:
      - "5000:5000"
